version: '3.7'

services:

  p1:
    image: sameersbn/squid
    networks:
      squid_net:
        ipv4_address: 10.0.0.2
    volumes:
      - "./p1.conf:/etc/squid/squid.conf"
    container_name: p1
    depends_on:
      - p2

  p2:
    image: sameersbn/squid
    networks:
      squid_net:
        ipv4_address: 10.0.0.3
    volumes:
      - "./p2.conf:/etc/squid/squid.conf"
    container_name: p2

  client:
    image: pmorski/alpine-curl
    networks:
      squid_net:
        ipv4_address: 10.0.0.4
    tty:
      true
    container_name: client

networks:
  squid_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
